language: ruby
rvm:
  - 2.1.1
install: bundle install --without development --deployment
cache:
  directories:
    - vendor/bundle
before_script: ruby migrate.rb
addons:
  code_climate:
    repo_token:
      secure: "c8ZzZa0NJycJ/uJZw8XG2CgHwBzkBOG17ZIFFXqvARmCJHgpu5Qkt4oSG9RUQOV4AaOMLzVjY7ry1ptGgxHi0nMGwQ8R65Xtq9jM6EfGmNrA0VpEGra8JQ5pYCaFi49zMjmFthEwm14EiSnIm2+OzfWbwSwYvwAapVG6YaR9gwI="
